/**
 * Seed danh muc khoa lam sang, ban kham va giuong noi bo tu file Excel nguon.
 * Nguon: c:\\Users\\admin\\Documents\\Google Drive\\BHYT\\danh muc benh vien\\DM\\FileMau_DANH_MUC_KHOA_LS_M01 (2).xlsx
 * Cap nhat: 2026-03-31
 */

export const PHIEN_BAN_DANH_MUC_KHOA_LS_M01 = '2026-03-31-m01-seed-17';

export const COT_DANH_MUC_KHOA_LS_M01 = [
  "STT",
  "MA_KHOA",
  "TEN_KHOA",
  "BAN_KHAM",
  "GIUONG_PD",
  "GIUONG_TK",
  "GIUONG_HSTC",
  "GIUONG_HSCC",
  "TU_NGAY",
  "DEN_NGAY",
  "MA_CSKCB",
  "ID",
  "MA_LOAI_KCB",
  "LDLK",
  "LIEN_KHOA",
  "GIUONG_2015"
];

export const DANH_MUC_KHOA_LS_M01 = [
  {
    "STT": 1,
    "MA_KHOA": "K47",
    "TEN_KHOA": "Khoa Xét nghiệm",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380362,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 2,
    "MA_KHOA": "K44",
    "TEN_KHOA": "Khoa Dược",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380363,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 3,
    "MA_KHOA": "K45",
    "TEN_KHOA": "Khoa Dinh dưỡng",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380364,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 4,
    "MA_KHOA": "K03",
    "TEN_KHOA": "Khoa Nội tổng hợp",
    "BAN_KHAM": "",
    "GIUONG_PD": 15,
    "GIUONG_TK": 15,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380410,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 5,
    "MA_KHOA": "K19",
    "TEN_KHOA": "Khoa Ngoại tổng hợp",
    "BAN_KHAM": "",
    "GIUONG_PD": 20,
    "GIUONG_TK": 20,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380411,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 6,
    "MA_KHOA": "K27",
    "TEN_KHOA": "Khoa Phụ sản",
    "BAN_KHAM": "",
    "GIUONG_PD": 40,
    "GIUONG_TK": 40,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380412,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 7,
    "MA_KHOA": "K18",
    "TEN_KHOA": "Khoa Nhi",
    "BAN_KHAM": "",
    "GIUONG_PD": 20,
    "GIUONG_TK": 20,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380413,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 8,
    "MA_KHOA": "K26",
    "TEN_KHOA": "Khoa Gây mê hồi sức",
    "BAN_KHAM": "",
    "GIUONG_PD": 5,
    "GIUONG_TK": 5,
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380414,
    "MA_LOAI_KCB": 4,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 9,
    "MA_KHOA": "03.18",
    "TEN_KHOA": "Nhi",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380416,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 10,
    "MA_KHOA": "15.28",
    "TEN_KHOA": "Tai - Mũi - Họng",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 380417,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 11,
    "MA_KHOA": "02.13",
    "TEN_KHOA": "Da liễu",
    "BAN_KHAM": 1,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 414848,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 12,
    "MA_KHOA": "02.03",
    "TEN_KHOA": "Nội tổng hợp",
    "BAN_KHAM": 3,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 414888,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 13,
    "MA_KHOA": "13.27",
    "TEN_KHOA": "Phụ sản",
    "BAN_KHAM": 6,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 445314,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 14,
    "MA_KHOA": "10.19",
    "TEN_KHOA": "Ngoại tổng hợp",
    "BAN_KHAM": 2,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 445315,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 15,
    "MA_KHOA": "K01",
    "TEN_KHOA": "Khoa Khám bệnh",
    "BAN_KHAM": 6,
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 461958,
    "MA_LOAI_KCB": 1,
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 16,
    "MA_KHOA": "K39",
    "TEN_KHOA": "Khoa Chẩn đoán hình ảnh",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 463941,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  },
  {
    "STT": 17,
    "MA_KHOA": "K43",
    "TEN_KHOA": "Khoa Chống nhiễm khuẩn",
    "BAN_KHAM": "",
    "GIUONG_PD": "",
    "GIUONG_TK": "",
    "GIUONG_HSTC": "",
    "GIUONG_HSCC": "",
    "TU_NGAY": "",
    "DEN_NGAY": "",
    "MA_CSKCB": "",
    "ID": 463942,
    "MA_LOAI_KCB": "",
    "LDLK": 2,
    "LIEN_KHOA": "",
    "GIUONG_2015": ""
  }
];
