/**
 * Theme + StyleSheet module quản trị BV.
 */
import { StyleSheet } from 'react-native';
import { CD } from '../../tien_ich/chu_de_giao_dien';

export const MAU = {
  nen: '#f8fafc',
  card: '#ffffff',
  vien: '#e2e8f0',
  chu: '#0f172a',
  chuPhu: '#64748b',
  chuNhat: '#94a3b8',
  accent: CD.mau_chinh || '#C2185B',
  accentNhat: '#fdf2f8',
  thanhCong: '#059669',
  canhBao: '#d97706',
  loi: '#dc2626',
  sidebar: '#0f172a',
  sidebarChu: '#e2e8f0',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: MAU.nen, minHeight: '100vh' },
  layout: { flex: 1, flexDirection: 'row' },
  sidebar: {
    width: 260,
    backgroundColor: MAU.sidebar,
    paddingVertical: 20,
    paddingHorizontal: 16,
    minHeight: '100vh',
  },
  logoWrap: { marginBottom: 24, paddingHorizontal: 4 },
  logoTitle: { fontSize: 17, fontWeight: '800', color: '#fff', letterSpacing: 0.3 },
  logoSub: { fontSize: 11, color: '#94a3b8', marginTop: 4, lineHeight: 16 },
  navItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 4,
  },
  navItemActive: { backgroundColor: 'rgba(194,24,91,0.25)' },
  navIcon: { fontSize: 18, marginRight: 10, width: 24, textAlign: 'center' },
  navLabel: { fontSize: 14, fontWeight: '600', color: MAU.sidebarChu, flex: 1 },
  navLabelActive: { color: '#fff', fontWeight: '700' },
  main: { flex: 1 },
  topBar: {
    backgroundColor: MAU.card,
    borderBottomWidth: 1,
    borderBottomColor: MAU.vien,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
  },
  topTitle: { fontSize: 20, fontWeight: '800', color: MAU.chu, flex: 1, minWidth: 200 },
  topSub: { fontSize: 12, color: MAU.chuPhu, marginTop: 2 },
  nutChinh: {
    backgroundColor: MAU.accent,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    cursor: 'pointer',
  },
  chuNutChinh: { color: '#fff', fontWeight: '700', fontSize: 13 },
  nutPhu: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: MAU.vien,
    cursor: 'pointer',
  },
  chuNutPhu: { fontSize: 13, fontWeight: '600', color: '#334155' },
  nutNguyHiem: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  chuNutNguyHiem: { fontSize: 12, fontWeight: '700', color: MAU.loi },
  hangThongKe: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, paddingHorizontal: 20, paddingVertical: 16 },
  theThongKe: {
    flex: 1,
    minWidth: 140,
    backgroundColor: MAU.card,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: MAU.vien,
    boxShadow: '0 1px 3px rgba(15,23,42,0.06)',
  },
  soThongKe: { fontSize: 28, fontWeight: '900', color: MAU.chu },
  nhanThongKe: { fontSize: 12, color: MAU.chuPhu, marginTop: 4, fontWeight: '600' },
  iconThongKe: { fontSize: 22, marginBottom: 8 },
  chonBvWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 20,
    paddingBottom: 12,
    alignItems: 'center',
  },
  chipBv: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: MAU.vien,
    cursor: 'pointer',
  },
  chipBvActive: { backgroundColor: MAU.accentNhat, borderColor: MAU.accent },
  chuChip: { fontSize: 13, color: '#334155', fontWeight: '600' },
  chuChipActive: { color: MAU.accent, fontWeight: '700' },
  badgeNguon: {
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
    marginLeft: 6,
  },
  badgeBundle: { backgroundColor: '#dbeafe', color: '#1d4ed8' },
  badgeCustom: { backgroundColor: '#dcfce7', color: '#15803d' },
  noiDung: { flex: 1 },
  noiDungPad: { padding: 20, paddingBottom: 48 },
  sectionHead: { marginBottom: 16 },
  tieuDeTab: { fontSize: 18, fontWeight: '800', color: MAU.chu },
  moTaTab: { fontSize: 13, color: MAU.chuPhu, marginTop: 6, lineHeight: 20 },
  hangTieuDe: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 10,
  },
  card: {
    backgroundColor: MAU.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: MAU.vien,
    boxShadow: '0 1px 3px rgba(15,23,42,0.05)',
  },
  cardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  cardBv: { flexGrow: 1, flexBasis: '30%', minWidth: 260, maxWidth: '100%' },
  tenCard: { fontSize: 16, fontWeight: '800', color: MAU.chu },
  meta: { fontSize: 12, color: MAU.chuPhu, marginTop: 6, lineHeight: 18 },
  hangNut: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  oNhap: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: '#fff',
    fontSize: 14,
    color: MAU.chu,
    marginBottom: 12,
  },
  nhan: { fontSize: 12, fontWeight: '700', color: '#475569', marginBottom: 6 },
  loi: { color: MAU.loi, fontWeight: '600', marginBottom: 12, fontSize: 13 },
  rong: { fontSize: 14, color: MAU.chuNhat, textAlign: 'center', paddingVertical: 32 },
  chipRole: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: MAU.vien,
    marginRight: 8,
    marginBottom: 6,
    cursor: 'pointer',
  },
  chipRoleActive: { backgroundColor: MAU.accentNhat, borderColor: MAU.accent },
  chuRoleActive: { color: MAU.accent, fontWeight: '700' },
  thanhTienDo: {
    height: 6,
    backgroundColor: '#e2e8f0',
    borderRadius: 3,
    marginTop: 8,
    overflow: 'hidden',
  },
  thanhTienDoFill: { height: '100%', backgroundColor: MAU.accent, borderRadius: 3 },
  dongAudit: {
    backgroundColor: MAU.card,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: MAU.accent,
    borderWidth: 1,
    borderColor: MAU.vien,
  },
  auditTime: { fontSize: 11, color: MAU.chuNhat, fontWeight: '600' },
  auditAction: { fontSize: 14, fontWeight: '700', color: MAU.chu, marginTop: 4 },
  mobileTabs: {
    flexDirection: 'row',
    backgroundColor: MAU.card,
    borderBottomWidth: 1,
    borderBottomColor: MAU.vien,
    paddingHorizontal: 4,
  },
  tabMobile: { flex: 1, alignItems: 'center', paddingVertical: 10 },
  tabMobileActive: { borderBottomWidth: 2, borderBottomColor: MAU.accent },
  modalNen: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.55)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    maxWidth: 560,
    width: '100%',
    alignSelf: 'center',
    maxHeight: '90%',
  },
  buocWizard: { flexDirection: 'row', marginBottom: 20, gap: 8 },
  buocItem: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
  },
  buocItemActive: { backgroundColor: MAU.accentNhat },
  buocItemDone: { backgroundColor: '#dcfce7' },
  chuBuoc: { fontSize: 11, fontWeight: '700', color: MAU.chuPhu },
  hangModal: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
});

export default styles;
